public class VerifyEntityResponse {
    public String ABN {get; set;}
    public String Name {get; set;}
    public String ACN {get; set;}
    public String ABNStatus {get; set;}
    public String GSTStatus {get; set;}
    public String EntityType {get; set;}
    public String RBN {get; set;}
    public String RBNState {get; set;}
    public String ACNStatusCode {get; set;}
    public String ACNStatus {get; set;}
    public String Locality {get; set;}
    public String State {get; set;}
    public String Postcode {get; set;}
    public Long ApiID {get; set;}
    
    public VerifyEntityResponse() {
        
    }
}