body{
	font-family:Arial, Helvetica, sans-serif; 
	font-size:13px;
}

warning {
	font-weight:bold;
	width: 99%; 
	display: inline-block;
	border: 1px solid;
	margin: 1px 1px;
	padding:5px 5px 5px 5px;
	background-repeat: no-repeat;
	background-position: 5px center;
	color: #00529B;
	background-color: #BDE5F8; 
}
actionBar{
	ont-weight:bold;
	width: 99%; 
	display: inline-block;
	border: 0px;
	margin: 1px 1px;
	padding:5px 5px 5px 5px;
	text-align: center; 	
}
img{
	vertical-align:middle;
}